// Home Voice community columns supplied and approved by the client.
// Keep the publication metadata, original issue links and PDF filenames exact.
export const homeVoiceArticles = [
  {
    slug: "true-cost-of-family-labor-business-profitability",
    subject: "Other Commentary",
    type: "Community Columns",
    publication: "Home Voice",
    author: "Dave Ananth",
    language: "Chinese",
    relationship: "Written by Dave Ananth; originally published in Home Voice, page 2",
    date: "28 August 2026",
    isoDate: "2026-08-28",
    title: "The True Cost of Family Labor: Why Your Business Might Not Be Making Money After All.",
    summary: "Dave Ananth examines how unpaid family labour can mask a business’s true profitability, and why fair wages and transparent records matter.",
    sourceUrl: "http://www.homevoice.co.nz/newEpaper/?jid=821397034790551552&iid=1543027157968752640&ino=2026-08-28",
    image: "/assets/articles/home-voice-family-labor-2026-08-28.jpg",
    imageAlt: "Home Voice Chinese-language column about family labour and business profitability, dated 28 August 2026, page 2, with Dave Ananth’s portrait.",
    imageWidth: 893,
    imageHeight: 1262,
    imagePresentation: "document",
    pdf: "articles/home-voice-family-labor-2026-08-28.pdf",
    contentHtml: `<h2>Article summary</h2><p>The article, authored by tax barrister Dave Ananth from Meridian Partners, addresses a common pitfall in family-run businesses where paper profits often mask underlying unprofitability because family members work long hours without receiving standard market wages. When evaluating a business for sale, potential buyers assess its true sustainable earning capacity by deducting the real market cost of replacing all unpaid or underpaid family labor with market-rate employees.</p><p>Failing to properly record wages or relying on unrecorded cash transactions creates significant legal, tax, and relational risks, including severe back-tax audits from Inland Revenue, wage compliance penalties, and internal family disputes. Ultimately, paying children and family members fair market wages and maintaining transparent financial books instills financial discipline, protects family trust, and presents a realistic, honest valuation that buyers can trust.</p>`,
  },
  {
    slug: "safeguarding-your-legacy-protecting-the-business-youve-built",
    subject: "Other Commentary",
    type: "Community Columns",
    publication: "Home Voice",
    author: "Dave Ananth",
    language: "Chinese",
    relationship: "Written by Dave Ananth; originally published in Home Voice",
    date: "7 August 2026",
    isoDate: "2026-08-07",
    title: "Safeguarding Your Legacy: Protecting the Business You’ve Built",
    summary: "Practical guidance for family-owned and immigrant businesses seeking to protect the reputation and long-term viability they have worked to build.",
    sourceUrl: "http://www.homevoice.co.nz/newEpaper/?jid=821397034790551552&iid=1535075690955804672&ino=2026-08-07",
    pdf: "articles/home-voice-1389-safeguarding-your-legacy.pdf",
    pdfDownloadName: "Home Voice Issue 1389 - Safeguarding Your Legacy.pdf",
    image: "/assets/articles/home-voice-1389-safeguarding-your-legacy.jpg",
    imageAlt: "Home Voice Chinese-language column Safeguarding Your Legacy, dated 7 August 2026, page 10, with Dave Ananth’s portrait.",
    imageWidth: 1240,
    imageHeight: 1755,
    imagePresentation: "document",
    contentHtml: `<p>Drawing on over three decades of legal experience in Malaysia and New Zealand, Meridian Partners partner and former Inland Revenue (IRD) prosecutor Dave Ananth offers practical guidance for family-owned and immigrant businesses seeking to protect their hard-earned legacies. He notes that most tax disasters rarely begin with intentional dishonesty, arising instead from undue optimism, delayed choices, and unmanaged cash-flow pressures that quietly compound into severe legal crises.</p><p>Ananth outlines essential strategies for safeguarding a business's reputation and long-term viability, emphasizing that genuine tax planning is about paying the exact amount required by law—claiming only what is permissible—to prevent disputes before they begin. He cautions against misusing PAYE withholding tax to cover short-term operational expenses, as IRD's modern digital cross-matching systems flag these discrepancies quickly. Ultimately, Ananth stresses that cutting corners on cheap advice or ignoring tax correspondence risks destroying in a moment what took a lifetime to build, urging business owners to make deliberate, well-advised decisions at every step.</p>`,
  },
  {
    slug: "mortgage-free-house-gold-coins-questions-at-ird",
    subject: "IRD Tax Debt",
    type: "Community Columns",
    publication: "Home Voice",
    author: "Dave Ananth",
    language: "Chinese",
    relationship: "Written by Dave Ananth; originally published in Home Voice",
    date: "14 August 2026",
    isoDate: "2026-08-14",
    title: "When a Mortgage-Free House and Gold Coins Raise Questions at IRD",
    summary: "A tax case about unexplained overseas transfers shows why contemporaneous records are essential when Inland Revenue asks where funds came from.",
    sourceUrl: "http://www.homevoice.co.nz/newEpaper/?jid=821397034790551552&iid=1537824639714201600&ino=2026-08-14",
    pdf: "articles/home-voice-1390-mortgage-free-house-gold-coins.pdf",
    pdfDownloadName: "Home Voice Issue 1390 - Mortgage-Free House and Gold Coins.pdf",
    image: "/assets/articles/home-voice-1390-mortgage-free-house-gold-coins.jpg",
    imageAlt: "Home Voice Chinese-language column about a mortgage-free house, gold coins and Inland Revenue questions, dated 14 August 2026, page 2.",
    imageWidth: 1240,
    imageHeight: 1755,
    imagePresentation: "document",
    contentHtml: `<p>A landmark tax case (TRA 023/15) involving a restaurant waitress who bought a mortgage-free house on modest declared earnings highlights the serious dangers of unverified overseas transfers and poor record-keeping. When an Inland Revenue (IRD) audit uncovered large, unexplained cash deposits, her explanations—ranging from sold gold coins to elderly parents' pensions—collapsed under cross-examination after a critical loan agreement was revealed to be backdated. Writing on this decision, Meridian Partners partner and tax barrister Dave Ananth uses the ruling to illustrate that while New Zealand does not tax family support, the legal burden of proof rests entirely on the taxpayer, and post-audit fabrications can trigger severe gross negligence penalties.</p><p>To safeguard genuine financial arrangements, Ananth emphasizes the necessity of documenting loans and gifts contemporaneously at the exact time funds move, maintaining complete paper trails with unedited digital metadata, and ensuring actual payment behaviors align strictly with written terms. Ultimately, he warns that while family affection is non-taxable, transferring substantial sums across borders requires clear, real-time proof—because a signed document created after an audit begins is merely paper in a nice suit.</p>`,
  },
  {
    slug: "you-take-what-you-need-vegetable-boxes-tax-records",
    subject: "Other Commentary",
    type: "Community Columns",
    publication: "Home Voice",
    author: "Dave Ananth",
    language: "Chinese",
    relationship: "Written by Dave Ananth; originally published in Home Voice",
    date: "21 August 2026",
    isoDate: "2026-08-21",
    title: "“You Take What You Need”: The Vegetable Boxes, Cabbage Leaves and Tax Records",
    summary: "A memorable audit story illustrates why receipts need context and why businesses should keep organised, contemporaneous tax records.",
    sourceUrl: "http://www.homevoice.co.nz/newEpaper/?jid=821397034790551552&iid=1540084865537712128&ino=2026-08-21",
    pdf: "articles/home-voice-1391-vegetable-boxes-tax-records.pdf",
    pdfDownloadName: "Home Voice Issue 1391 - Vegetable Boxes and Tax Records.pdf",
    image: "/assets/articles/home-voice-1391-vegetable-boxes-tax-records.jpg",
    imageAlt: "Home Voice Chinese-language column about vegetable boxes, cabbage leaves and tax records, dated 21 August 2026, page 2.",
    imageWidth: 1240,
    imageHeight: 1755,
    imagePresentation: "document",
    contentHtml: `<p>A memorable audit case involving a taxpayer who handed over a box of crumpled receipts mixed with withered cabbage leaves serves as the focal point for Meridian Partners tax partner and former Inland Revenue prosecutor Dave Ananth's discussion on proper tax record management. Ananth uses this anecdote to warn that while technology has advanced, the physical "vegetable box" has simply morphed into digital clutter—such as thousands of unindexed phone photos and scattered chat logs. He emphasizes that a receipt alone merely proves money left an account, not why it was spent or whether it legally qualifies as a business deduction, a vulnerability that modern AI-driven tax audits will quickly expose.</p><p>To safeguard a business, Ananth advises establishing consistent routines by logging full transaction context at the time of purchase, immediately documenting cash transactions and family loans in writing, and maintaining organized records for at least seven tax years as required by New Zealand law. Ultimately, he stresses that clean, contemporaneous documentation saves time, lowers professional fees, and locks in crucial facts before memories fade—allowing business owners to present clear proof instantly while leaving the "cabbage leaves" behind.</p>`,
  },
];
